const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const imageTypes = new Set(['.png', '.jpg', '.jpeg', '.webp', '.gif', '.avif']);
const videoTypes = new Set(['.mp4', '.webm', '.ogv', '.ogg', '.m4v']);
function scan() {
  const games = JSON.parse(fs.readFileSync(path.join(root, 'games.json'), 'utf8'));
  return games.map(game => {
    const folder = path.resolve(root, game.folder);
    if (!folder.startsWith(path.join(root, 'assets', 'games') + path.sep)) throw new Error('Invalid game folder');
    const media = {screenshots: [], videos: []};
    function walk(dir) {
      if (!fs.existsSync(dir)) return;
      for (const entry of fs.readdirSync(dir, {withFileTypes:true}).sort((a,b)=>a.name.localeCompare(b.name))) {
        if (entry.isSymbolicLink()) continue;
        const file = path.join(dir, entry.name);
        if (entry.isDirectory()) { walk(file); continue; }
        const ext = path.extname(file).toLowerCase();
        const type = imageTypes.has(ext) ? 'screenshots' : videoTypes.has(ext) ? 'videos' : null;
        if (type && entry.isFile()) media[type].push(path.relative(root, file).split(path.sep).map(encodeURIComponent).join('/'));
      }
    }
    walk(folder);
    return {...game, ...media};
  });
}
function build() {
  const games = scan();
  fs.writeFileSync(path.join(root, 'games-data.js'), '/* Generated by UPDATE-MEDIA.cmd. Edit games.json for game information. */\nvar GAMES = '+JSON.stringify(games,null,2)+';\n');
  fs.writeFileSync(path.join(root, 'media-manifest.json'), JSON.stringify(games,null,2)+'\n');
  return games;
}
if (require.main === module) console.log('Updated media for '+build().length+' games and demos.');
module.exports = {scan, build, root};
